### ISSUE TITLE
New version with support for handling 1 error

### ISSUE THREAD

**Issue by FlymeDllVa** [vikstrous/dataloadgen#10]
Can you put tag on the master by making a new version with support for handling 1 error.

https://github.com/vikstrous/dataloadgen/blob/bf86f1fc183a6331923c2d6731406364b3c57630/dataloadgen.go#L127

**Comment by FlymeDllVa** [comment]
@vikstrous help plz

**Comment by vikstrous** [comment]
Sorry for the delay. I'll tag master as a release now.
