### ISSUE TITLE
Panic Recovery

### ISSUE THREAD

**Issue by pbedat** [vikstrous/dataloadgen#15]
I think I've discovered a little footgun in your library:
When launching goroutines, that execute user code in a library, I would either take care of panic recovery from the user or write about the absence of it in the docs.

E.g. Implementing a loader that panics, will terminate an application, even if there is a recovery handler in the http pipeline. One would guess that the `dataloadgen.Loader` might recover from panics, but it doesn't.
While this can easily be solved by wrapping the fetch function, we could also implement recovery in the loader itself or be a little bit more upfront about it in the docs.

What do you think about it?

PS: Thanks for your great work. I appreciate working with this lib!

**Comment by vikstrous** [comment]
Yeah, makes sense to have a default panic handler and if the user wants to add their own inside the fetch function, it will supersede the default one anyway.
