### ISSUE TITLE
return a type that implements error from LoadAll methods

### ISSUE THREAD

**Issue by vikstrous2** [vikstrous/dataloadgen#3]
I think it might be better to return a typed array of errors that implements `error` rather than a raw `[]error`. This is probably mostly backwards compatible.

**Comment by vikstrous** [comment]
done in https://github.com/vikstrous/dataloadgen/commit/27a2990a0d298526a050f02cab69c41205a50a26

**Comment by vikstrous** [comment]
It wasn't very backwards compatible... but I'm still calling this package v0, so I went ahead with it.
